2025-03-22 11:14:13 - 99 - launch_app - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-22 11:14:14 - 99 - launch_app - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-22 11:14:14 - 99 - launch_app - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-22 11:14:59 - 74 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-22 11:14:59 - 75 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-22 11:14:59 - 94 - launch_app - [INFO] - Successfully launched the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-22 11:15:02 - 74 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-22 11:15:02 - 75 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-22 11:15:02 - 94 - launch_app - [INFO] - Successfully launched the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-22 11:15:03 - 74 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-22 11:15:03 - 75 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-22 11:15:03 - 94 - launch_app - [INFO] - Successfully launched the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-22 11:15:03 - 74 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-22 11:15:03 - 75 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-22 11:15:03 - 94 - launch_app - [INFO] - Successfully launched the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-22 11:15:03 - 74 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-22 11:15:03 - 75 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-22 11:15:03 - 94 - launch_app - [INFO] - Successfully launched the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-22 11:17:17 - 74 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-22 11:17:17 - 75 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-22 11:17:17 - 94 - launch_app - [INFO] - Successfully launched the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-22 11:23:14 - 74 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-22 11:23:14 - 75 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-22 11:23:14 - 94 - launch_app - [INFO] - Successfully launched the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-22 11:23:42 - 74 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-22 11:23:42 - 75 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-22 11:23:44 - 94 - launch_app - [INFO] - Successfully launched the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-22 11:24:09 - 74 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-22 11:24:09 - 75 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-22 11:24:22 - 94 - launch_app - [INFO] - Successfully launched the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-22 11:41:27 - 74 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-22 11:41:27 - 75 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-22 11:43:16 - 74 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-22 11:43:16 - 75 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-22 11:43:20 - 74 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-22 11:43:20 - 75 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-28 23:08:01 - 74 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-28 23:08:01 - 75 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-28 23:08:03 - 74 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-28 23:08:03 - 75 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-28 23:08:08 - 172 - check_dict - [ERROR] - Error: Command dictionary does not contain 'path' key.
2025-03-28 23:08:09 - 172 - check_dict - [ERROR] - Error: Command dictionary does not contain 'path' key.
2025-03-28 23:08:14 - 94 - launch_app - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-28 23:08:15 - 94 - launch_app - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-28 23:08:16 - 74 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-28 23:08:16 - 75 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-28 23:08:33 - 94 - launch_app - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-28 23:08:35 - 172 - check_dict - [ERROR] - Error: Command dictionary does not contain 'path' key.
2025-03-28 23:08:35 - 172 - check_dict - [ERROR] - Error: Command dictionary does not contain 'path' key.
2025-03-28 23:08:37 - 74 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-28 23:08:37 - 75 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-28 23:13:32 - 70 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-28 23:13:32 - 71 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-28 23:27:06 - 70 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-28 23:27:06 - 71 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-28 23:27:08 - 70 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-28 23:27:08 - 71 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-28 23:37:07 - 70 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-28 23:37:07 - 71 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-28 23:37:08 - 115 - stop_script - [INFO] - Terminating the process for button: Stop Script
2025-03-28 23:37:11 - 70 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-28 23:37:11 - 71 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-28 23:37:12 - 115 - stop_script - [INFO] - Terminating the process for button: Stop Script
2025-03-28 23:37:14 - 70 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-28 23:37:14 - 71 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-28 23:37:16 - 92 - run_script - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-28 23:37:21 - 92 - run_script - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-28 23:37:22 - 92 - run_script - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-28 23:37:25 - 70 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-28 23:37:25 - 71 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-28 23:37:27 - 92 - run_script - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-28 23:37:28 - 194 - check_dict - [ERROR] - Error: Command dictionary does not contain 'path' key.
2025-03-28 23:37:30 - 194 - check_dict - [ERROR] - Error: Command dictionary does not contain 'path' key.
2025-03-28 23:37:31 - 92 - run_script - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-29 13:44:35 - 70 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-29 13:44:35 - 71 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-29 13:44:37 - 115 - stop_script - [INFO] - Terminating the process for button: Stop Script
2025-03-29 13:44:39 - 70 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-29 13:44:39 - 71 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-29 13:44:40 - 115 - stop_script - [INFO] - Terminating the process for button: Stop Script
2025-03-29 13:49:49 - 70 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-29 13:49:49 - 71 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-29 13:49:50 - 70 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-29 13:49:50 - 71 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-29 13:49:52 - 92 - run_script - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-29 13:49:55 - 92 - run_script - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-29 13:49:56 - 194 - check_dict - [ERROR] - Error: Command dictionary does not contain 'path' key.
2025-03-29 13:49:57 - 115 - stop_script - [INFO] - Terminating the process for button: Stop Script
2025-03-29 13:49:59 - 92 - run_script - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-29 13:51:24 - 70 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-29 13:51:24 - 71 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-29 13:51:25 - 115 - stop_script - [INFO] - Terminating the process for button: Stop Script
2025-03-29 15:56:12 - 71 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-29 15:56:12 - 72 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-29 15:56:41 - 71 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-29 15:56:41 - 72 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-29 15:56:42 - 116 - stop_script - [INFO] - Sending SIGINT to the process for button: Stop Script
2025-03-30 12:02:53 - 71 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:02:53 - 72 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:03:50 - 71 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:03:50 - 72 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:03:51 - 124 - stop_script - [INFO] - Sending SIGINT to the process for button: Stop Script
2025-03-30 12:03:54 - 71 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:03:54 - 72 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:03:56 - 124 - stop_script - [INFO] - Sending SIGINT to the process for button: Stop Script
2025-03-30 12:03:57 - 101 - run_script - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-30 12:03:58 - 101 - run_script - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-30 12:04:11 - 71 - run_script - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-30 12:04:11 - 72 - run_script - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-30 12:04:13 - 101 - run_script - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-30 12:04:14 - 101 - run_script - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-30 12:04:15 - 101 - run_script - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-30 12:04:16 - 213 - check_dict - [ERROR] - Error: Command dictionary does not contain 'path' key.
2025-03-30 12:04:18 - 213 - check_dict - [ERROR] - Error: Command dictionary does not contain 'path' key.
2025-03-30 12:10:58 - 72 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:10:58 - 73 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:11:14 - 72 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:11:14 - 73 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:11:19 - 72 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-30 12:11:19 - 73 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-30 12:12:41 - 72 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:12:41 - 73 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:12:41 - 89 - launch_app - [ERROR] - Error launching the application: system() takes at most 1 argument (2 given)
Traceback (most recent call last):
  File "c:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\src\__init__.py", line 77, in launch_app
    os.system(f"start cmd /k", f"python {cmd}")
TypeError: system() takes at most 1 argument (2 given)
2025-03-30 12:12:57 - 72 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:12:57 - 73 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:16:17 - 72 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:16:17 - 73 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:16:22 - 72 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-30 12:16:22 - 73 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test.py
2025-03-30 12:16:34 - 72 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:16:34 - 73 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:16:44 - 72 - launch_app - [DEBUG] - Launching the application: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:16:44 - 73 - launch_app - [DEBUG] - Command: C:\Users\nicol\OneDrive\Documents\Github-Projects\Python_Script_Launcher\tests\test2.py
2025-03-30 12:16:51 - 163 - check_dict - [ERROR] - Error: Command dictionary does not contain 'path' key.
2025-03-30 12:16:53 - 163 - check_dict - [ERROR] - Error: Command dictionary does not contain 'path' key.
2025-03-30 12:16:55 - 86 - launch_app - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-30 12:17:36 - 104 - check_path_format - [ERROR] - Path format is incorrect for Windows systems. Separator: '\' is required. 
>> Path: C:/ExampleFolder/ExampleScript.py
2025-03-30 12:17:36 - 104 - check_path_format - [ERROR] - Path format is incorrect for Windows systems. Separator: '\' is required. 
>> Path: C:/ExampleFolder/ExampleScript.py
2025-03-30 12:17:37 - 104 - check_path_format - [ERROR] - Path format is incorrect for Windows systems. Separator: '\' is required. 
>> Path: C:/ExampleFolder/ExampleScript.py
2025-03-30 12:17:37 - 86 - launch_app - [ERROR] - Error: The script 'C:\ExampleFolder\ExampleScript.py' does not exist.
2025-03-30 12:17:38 - 163 - check_dict - [ERROR] - Error: Command dictionary does not contain 'path' key.
2025-03-30 12:17:38 - 163 - check_dict - [ERROR] - Error: Command dictionary does not contain 'path' key.
